export const REQUIRED_CROSSAGE_METHODS = [
  "invoke",
  "chooseFolder",
  "chooseDamCatalog",
  "chooseOpenPhotoCatalog",
  "chooseImages",
  "chooseAudioFile",
  "chooseJsonFile",
  "chooseModelFile",
  "chooseColorProfileFile",
  "getPathForFile",
  "prepareMedia",
  "saveCameraFrame",
  "cancelScan",
  "cancelMediaAction",
  "pauseScan",
  "resumeScan",
  "getScanMarkerStatus",
  "startFolderWatch",
  "stopFolderWatch",
  "getPhotoTetherStatus",
  "startPhotoTether",
  "stopPhotoTether",
  "resumePhotoTether",
  "capturePhotoTether",
  "getSystemIntegration",
  "setLaunchAtLogin",
  "getUpdateStatus",
  "checkForUpdates",
  "setUpdateChannel",
  "downloadUpdate",
  "installUpdate",
  "getDiagnosticsReport",
  "exportDiagnosticsReport",
  "recordDiagnosticEvent",
  "getPhotoIndexingRuntimeStatus",
  "getPhotoSources",
  "getPhotoCatalogStatus",
  "inspectOpenPhotoCatalog",
  "exportOpenPhotoCatalog",
  "importOpenPhotoCatalog",
  "cancelOpenPhotoCatalog",
  "getDamCatalogStatus",
  "listDamCatalogs",
  "previewDamCatalog",
  "importDamCatalog",
  "syncDamCatalog",
  "getPhotosSensitiveAuthStatus",
  "authenticatePhotosSensitiveAccess",
  "getWorkspaceLockStatus",
  "enableWorkspaceLock",
  "lockWorkspace",
  "unlockWorkspace",
  "disableWorkspaceLock",
  "getWorkspaceEncryptionStatus",
  "createWorkspaceRecoveryCode",
  "rotateWorkspaceEncryptionKey",
  "revealPath",
  "openPath",
  "openPhotoPrivacySettings",
  "openPathWith",
  "listExternalEditors",
  "forgetExternalEditor",
  "sharePaths",
  "printPath",
  "writeClipboardText",
  "writeClipboardImagePath",
  "startFileDrag",
  "getInitialState",
  "rendererReady",
  "setAppLanguage",
  "getMcpConnectionInfo",
  "addMcpToCodex",
  "revealMcpConfigs",
  "revealOrBuildMcpBundle",
  "startMcpHttpServer",
  "stopMcpHttpServer",
  "getMcpHttpStatus",
  "onMcpHttpStatus",
  "getMobileCompanionStatus",
  "configureMobileCompanion",
  "createMobileCompanion",
  "revokeMobileCompanion",
  "onAppCommand",
  "onExternalOpen",
  "onScanProgress",
  "onBackendStartup",
  "onFolderWatch",
  "onPhotoTether",
  "onBackendError",
  "onUpdateStatus",
  "onDiagnosticsEvent"
] as const;

export function missingCrossAgeBridgeMembers(candidate: unknown) {
  if (!candidate || typeof candidate !== "object") {
    return ["crossAge", "platform", ...REQUIRED_CROSSAGE_METHODS];
  }
  const bridge = candidate as Record<string, unknown>;
  const missing: string[] = REQUIRED_CROSSAGE_METHODS.filter((name) => typeof bridge[name] !== "function");
  if (typeof bridge.platform !== "string") {
    missing.unshift("platform");
  }
  return missing;
}

export function isCrossAgeBridgeReady(candidate: unknown) {
  return missingCrossAgeBridgeMembers(candidate).length === 0;
}
