const { contextBridge, ipcRenderer, webUtils } = require("electron");

const TRUSTED_BACKEND_COMMANDS = new Set([
  "get_state",
  "model_status",
  "model_lifecycle_status",
  "run_model_lifecycle_evaluation",
  "stage_model_lifecycle_candidate",
  "promote_model_lifecycle_candidate",
  "rollback_model_lifecycle_baseline",
  "rollback_model_configuration",
  "set_model_root",
  "download_model",
  "set_workspace",
  "set_consent",
  "enroll",
  "enroll_paths",
  "enroll_age_groups",
  "synthetic_enrollment_screen_status",
  "approve_synthetic_enrollment_review",
  "reject_synthetic_enrollment_review",
  "build_age_trajectory_references",
  "remove_age_trajectory_references",
  "synthetic_age_image_review_status",
  "generate_synthetic_age_image_reviews",
  "approve_synthetic_age_image_review",
  "reject_synthetic_age_image_review",
  "scan",
  "scan_paths",
  "cancel_scan",
  "pause_scan",
  "resume_scan",
  "scan_job_status",
  "analyze_folder",
  "folder_tree",
  "set_status",
  "bulk_set_status",
  "set_candidate_note",
  "block_false_match",
  "bulk_block_false_matches",
  "reassign_candidate_person",
  "bulk_reassign_candidate_person",
  "duplicate_people",
  "apply_review_rules",
  "query_candidates",
  "ordered_review_candidates",
  "suggest_photo_review_more_candidates",
  "suggest_photo_relationship_names",
  "review_photo_relationship_name_suggestion",
  "list_photo_folders",
  "list_photo_folder_items",
  "list_photo_date_buckets",
  "search_photo_library",
  "semantic_search_photos",
  "photo_library_agent_status",
  "query_photo_library_agent",
  "execute_photo_library_agent_plan",
  "list_photo_assets",
  "list_photo_burst_stacks",
  "set_photo_burst_selection",
  "list_photo_keywords",
  "save_photo_keyword",
  "delete_photo_keyword",
  "export_photo_keywords",
  "import_photo_keywords",
  "save_photo_person_profile",
  "save_photo_pet_profile",
  "save_photo_place_profile",
  "save_photo_utility_profile",
  "rename_photo_pet",
  "assign_photo_pet",
  "bulk_assign_photo_pet",
  "dismiss_photo_pet_review",
  "bulk_dismiss_photo_pet_review",
  "save_photo_people_group",
  "delete_photo_people_group",
  "update_photo_asset_metadata",
  "update_photo_assets_metadata",
  "reverse_geocode_photo_location",
  "get_photo_edit_stack",
  "get_photo_edit_stacks",
  "save_photo_edit_stack",
  "save_photo_edit_stacks",
  "revert_photo_edit_stack",
  "list_photo_edit_stack_versions",
  "create_photo_edit_stack_version",
  "restore_photo_edit_stack_version",
  "delete_photo_edit_stack_version",
  "photo_generative_status",
  "photo_content_credentials_status",
  "inspect_photo_content_credentials",
  "install_photo_generative_pack",
  "render_photo_generative_preview",
  "apply_photo_generative_edit",
  "discard_photo_generative_preview",
  "photo_story_status",
  "photo_stories",
  "generate_photo_story",
  "save_photo_story",
  "delete_photo_story",
  "restore_photo_story_version",
  "export_photo_story",
  "create_photo_story_slideshow",
  "photo_culling_status",
  "analyze_photo_burst_culling",
  "apply_photo_culling_recommendation",
  "duplicate_photo_asset_version",
  "duplicate_photo_asset_rendered_version",
  "record_photo_asset_event",
  "apply_photo_visibility_operation",
  "list_photo_operations",
  "photo_restore_rehearsal",
  "photo_backup_restore_rehearsal",
  "undo_photo_operation",
  "permanently_delete_photos",
  "merge_photo_duplicates",
  "dismiss_photo_duplicate_group",
  "import_photos",
  "photo_source_status",
  "photo_source_jobs",
  "photo_source_job_status",
  "run_photo_source_job",
  "cancel_photo_source_job",
  "retry_photo_source_job",
  "dismiss_photo_source_job",
  "list_photo_source_people_hints",
  "review_photo_source_people_hint",
  "revoke_photo_source_consent",
  "apple_photos_status",
  "list_apple_photos_libraries",
  "preview_apple_photos_library",
  "import_apple_photos_library",
  "sync_apple_photos_library",
  "export_apple_photos_assets",
  "windows_photo_source_status",
  "list_windows_photo_folders",
  "preview_windows_photo_folder",
  "import_windows_photo_folder",
  "sync_windows_photo_folder",
  "update_photo_import_session_provenance",
  "bulk_update_photo_import_session_provenance",
  "archive_photo_import_sessions",
  "list_photo_import_failures",
  "dismiss_photo_import_failure",
  "retry_photo_import_failure",
  "save_recovered_photo_import_failure",
  "delete_recovered_photo_import_failure",
  "scan_photo_recovered_orphans",
  "photo_recovered_cleanup",
  "rebuild_photo_previews",
  "photo_library_preview_sweep",
  "relink_photo_library_paths",
  "create_photo_media_pair",
  "relink_photo_media_pair",
  "delete_photo_media_pair",
  "consolidate_photo_library_assets",
  "photo_library_backup_check",
  "photo_library_catalog_cleanup",
  "photo_repair_history",
  "photo_library_settings",
  "save_photo_library_settings",
  "index_photo_ocr",
  "photo_ocr_index_status",
  "index_photo_barcodes",
  "photo_barcode_index_status",
  "photo_vlm_status",
  "install_photo_vlm",
  "index_photo_objects",
  "photo_object_index_status",
  "photo_audio_status",
  "photo_audio_segments",
  "index_photo_audio",
  "local_sync_status",
  "local_sync_initialize",
  "local_sync_start",
  "local_sync_stop",
  "local_sync_create_invitation",
  "local_sync_accept_invitation",
  "local_sync_sync_peer",
  "local_sync_revoke_peer",
  "local_sync_conflicts",
  "local_sync_export_recovery",
  "local_sync_restore_recovery",
  "enqueue_photo_indexing_job",
  "photo_indexing_jobs",
  "run_photo_indexing_job",
  "run_photo_indexing_queue",
  "cancel_photo_indexing_job",
  "dismiss_photo_indexing_job",
  "photo_curation_preferences",
  "save_photo_curation_preferences",
  "photo_user_memories",
  "photo_user_memory_source_order",
  "save_photo_user_memory",
  "delete_photo_user_memory",
  "photo_slideshow_theme_templates",
  "save_photo_slideshow_theme_template",
  "delete_photo_slideshow_theme_template",
  "export_photo_slideshow_theme_templates",
  "import_photo_slideshow_theme_templates",
  "photo_slideshow_projects",
  "save_photo_slideshow_project",
  "delete_photo_slideshow_project",
  "export_photo_slideshow",
  "export_photo_memory_movie",
  "list_photo_saved_filters",
  "save_photo_saved_filter",
  "delete_photo_saved_filter",
  "preview_photo_album_rules",
  "save_photo_album",
  "delete_photo_album",
  "merge_photo_albums",
  "migrate_photo_smart_albums",
  "list_photo_album_folders",
  "save_photo_album_folder",
  "delete_photo_album_folder",
  "move_photo_album_to_folder",
  "reorder_photo_album_folder_children",
  "photo_album_source_order",
  "add_photo_album_items",
  "remove_photo_album_items",
  "reorder_photo_album_items",
  "suggest_photo_albums",
  "photo_color_profile_status",
  "validate_photo_color_profile",
  "start_photo_export_job",
  "photo_export_job_status",
  "photo_export_jobs",
  "cancel_photo_export_job",
  "export_photo_selection",
  "export_photo_contact_sheet",
  "export_photo_video_frame",
  "export_photo_video_trim",
  "export_photo_live_motion",
  "export_photo_subject_cutout",
  "export_photo_portrait_blur",
  "set_photo_live_key_photo",
  "reset_photo_live_key_photo",
  "set_photo_video_poster",
  "reset_photo_video_poster",
  "clear_queue",
  "purge_candidates",
  "purge_duplicate_candidates",
  "prepare_previews",
  "delete_reference",
  "delete_person",
  "delete_subject_data",
  "compliance_status",
  "biometric_retention_policy",
  "acknowledge_ai_disclosure",
  "enforce_retention_policy",
  "export_biometric_retention_policy",
  "record_biometric_policy_publication",
  "rename_person",
  "clear_references",
  "purge_old_candidates",
  "repair_workspace",
  "database_integrity",
  "repair_database_integrity",
  "relink_workspace_paths",
  "export_report",
  "export_workspace_inventory",
  "export_audit_log",
  "export_consent_receipt",
  "retention_policy_report",
  "export_safe_mode_audit",
  "model_drift_report",
  "reference_gap_report",
  "export_review_ledger",
  "export_scan_history",
  "export_workspace_backup",
  "verify_workspace_backup",
  "restore_workspace_backup",
  "prune_workspace_backups",
  "prune_scan_manifests",
  "export_candidates",
  "preview_candidate_media_action",
  "manage_candidate_media",
  "media_action_history",
  "restore_media_action",
  "retry_media_action",
  "undo_media_action",
  "media_trash_report",
  "cleanup_media_trash",
  "export_media_bundle",
  "workspace_health",
  "runtime_self_test",
  "runtime_benchmark",
  "benchmark_history",
  "storage_io_benchmark",
  "release_readiness",
  "model_integrity",
  "model_distribution_audit",
  "model_switch_dry_run",
  "backfill_model_references",
  "export_support_bundle",
  "installer_self_diagnostics",
  "public_dataset_catalog",
  "inspect_public_dataset",
  "run_public_dataset_benchmark",
  "run_cross_age_trajectory_benchmark",
  "compare_public_dataset_models",
  "apply_model_recommendation",
  "calibration_summary",
  "accuracy_evaluation",
  "generate_accuracy_validation_pack",
  "run_accuracy_validation_pack",
  "accuracy_validation_history",
  "self_learning_rd_status",
  "calibration_learning_status",
  "run_learning_jobs",
  "reference_suggestion_status",
  "stage_reference_suggestions",
  "approve_reference_suggestion",
  "reject_reference_suggestion",
  "stage_calibration",
  "promote_calibration",
  "rollback_calibration",
  "embedding_adapter_status",
  "stage_embedding_adapter",
  "promote_embedding_adapter",
  "rollback_embedding_adapter",
  "apply_calibration",
  "apply_personalized_calibration",
  "export_accuracy_labels",
  "import_accuracy_labels",
  "export_training_examples",
  "import_training_examples",
  "privacy_report",
  "delete_face_data",
  "optimize_workspace",
  "enforce_storage_budget",
  "add_calibration_label",
  "set_performance_mode",
  "save_settings",
  "calibrate_safe_mode",
  "explain_safety",
  "install_safety_explainer",
  "list_safe_mode_flagged",
  "set_photo_safe_mode_override",
  "audit_events",
  "audit_chain_status",
  "list_jurisdictions",
  "set_jurisdiction_preset",
  "export_compliance_pack",
  "export_examination_report",
  "list_workspaces",
  "add_workspace"
]);

function assertPlainObject(value, label = "Payload") {
  if (!value || typeof value !== "object" || Array.isArray(value)) {
    throw codedError("E-IPC-PAYLOAD", `${label} must be an object.`);
  }
}

function codedError(code, message) {
  const error = new Error(`[${code}] ${message}`);
  error.code = code;
  return error;
}

function normalizeIpcError(error) {
  const raw = error instanceof Error ? error.message : String(error || "The action failed.");
  const cleaned = raw
    .replace(/^Error invoking remote method '[^']+':\s*/i, "")
    .replace(/^Error:\s*/i, "")
    .trim();
  const code = cleaned.match(/\b([EW]-[A-Z0-9-]{2,})\b/)?.[1] || "";
  const message = cleaned.replace(/^\[[EW]-[A-Z0-9-]{2,}\]\s*/, "").trim() || "The action failed.";
  const normalized = new Error(code ? `[${code}] ${message}` : message);
  if (code) {
    normalized.code = code;
  }
  if (error instanceof Error && error.stack) {
    normalized.stack = error.stack;
  }
  return normalized;
}

function safeInvoke(channel, payload) {
  return ipcRenderer.invoke(channel, payload).catch((error) => {
    throw normalizeIpcError(error);
  });
}

function invokeBackend(command, params = {}) {
  const safeCommand = String(command || "");
  if (!TRUSTED_BACKEND_COMMANDS.has(safeCommand)) {
    throw codedError("E-IPC-BLOCKED-COMMAND", `Blocked backend command: ${safeCommand || "empty"}.`);
  }
  assertPlainObject(params, "Command params");
  return safeInvoke("backend:invoke", { command: safeCommand, params });
}

function subscribe(channel, callback) {
  if (typeof callback !== "function") {
    throw codedError("E-IPC-PAYLOAD", "Listener must be a function.");
  }
  const listener = (_event, payload) => callback(payload);
  ipcRenderer.on(channel, listener);
  return () => ipcRenderer.removeListener(channel, listener);
}

const safePlatform = typeof process !== "undefined" ? process.platform : "unknown";
const safeEnv = typeof process !== "undefined" && process.env ? process.env : {};

contextBridge.exposeInMainWorld("crossAge", Object.freeze({
  invoke: invokeBackend,
  chooseFolder: () => safeInvoke("dialog:choose-folder"),
  chooseDamCatalog: (provider) => safeInvoke("dialog:choose-dam-catalog", { provider: String(provider || "") }),
  chooseOpenPhotoCatalog: () => safeInvoke("dialog:choose-open-photo-catalog"),
  // Multi-select image/video file picker for the "Add a person" flow. Returns
  // [{ path, url }] where url is a vintrace-media:// thumbnail URL (main grants
  // each path so the protocol can serve it).
  chooseImages: () => safeInvoke("dialog:choose-images"),
  chooseAudioFile: () => safeInvoke("dialog:choose-audio"),
  chooseJsonFile: () => safeInvoke("dialog:choose-json"),
  chooseModelFile: () => safeInvoke("dialog:choose-model"),
  chooseColorProfileFile: () => safeInvoke("dialog:choose-color-profile"),
  // Resolve a dropped File to its absolute path. webUtils is available even in a
  // sandboxed preload; this is the supported Electron way to read a drop path.
  getPathForFile: (file) => {
    try {
      return webUtils.getPathForFile(file) || "";
    } catch (_error) {
      return "";
    }
  },
  // Grant a batch of file/folder paths and get their thumbnail URLs back, so
  // dropped or folder-sampled images can be previewed before enrolling.
  prepareMedia: (paths) => safeInvoke("media:prepare-paths", { paths: Array.isArray(paths) ? paths : [] }),
  saveCameraFrame: (dataUrl) => safeInvoke("camera:save-frame", { dataUrl }),
  cancelScan: () => safeInvoke("scan:cancel"),
  cancelMediaAction: () => safeInvoke("media-action:cancel"),
  pauseScan: () => safeInvoke("scan:pause"),
  resumeScan: () => safeInvoke("scan:resume"),
  getScanMarkerStatus: () => safeInvoke("scan:marker-status"),
  startFolderWatch: (folder) => {
    if (typeof folder !== "string" || !folder.trim()) {
      return Promise.reject(codedError("E-FOLDER-WATCH-PATH", "Choose a folder to watch."));
    }
    return safeInvoke("folder-watch:start", { folder });
  },
  stopFolderWatch: () => safeInvoke("folder-watch:stop"),
  getPhotoTetherStatus: (refreshCamera = false) => safeInvoke("photo-tether:status", { refreshCamera: Boolean(refreshCamera) }),
  startPhotoTether: (options = {}) => {
    assertPlainObject(options, "Photo tether options");
    return safeInvoke("photo-tether:start", options);
  },
  stopPhotoTether: () => safeInvoke("photo-tether:stop"),
  resumePhotoTether: (sessionId) => safeInvoke("photo-tether:resume", { sessionId: String(sessionId || "") }),
  capturePhotoTether: () => safeInvoke("photo-tether:capture"),
  getSystemIntegration: () => safeInvoke("system:get-integration"),
  setLaunchAtLogin: (openAtLogin) => safeInvoke("system:set-launch-at-login", { openAtLogin }),
  getUpdateStatus: () => safeInvoke("updater:get-status"),
  checkForUpdates: () => safeInvoke("updater:check"),
  setUpdateChannel: (channel) => safeInvoke("updater:set-channel", { channel }),
  downloadUpdate: () => safeInvoke("updater:download"),
  installUpdate: () => safeInvoke("updater:install"),
  getDiagnosticsReport: (includePaths = false) => safeInvoke("diagnostics:get-report", { includePaths }),
  exportDiagnosticsReport: (includePaths = false) => safeInvoke("diagnostics:export-report", { includePaths }),
  recordDiagnosticEvent: (event) => safeInvoke("diagnostics:record-event", event && typeof event === "object" ? event : { message: String(event || "") }),
  getPhotoIndexingRuntimeStatus: () => safeInvoke("photo-indexing-runtime:get-status"),
  getPhotoSources: () => safeInvoke("photos:get-sources"),
  getPhotoCatalogStatus: () => safeInvoke("photo-catalog:status"),
  inspectOpenPhotoCatalog: (payload) => {
    assertPlainObject(payload, "Open catalog inspection payload");
    return safeInvoke("photo-catalog:inspect", payload);
  },
  exportOpenPhotoCatalog: (payload) => {
    assertPlainObject(payload, "Open catalog export payload");
    return safeInvoke("photo-catalog:export", payload);
  },
  importOpenPhotoCatalog: (payload) => {
    assertPlainObject(payload, "Open catalog import payload");
    return safeInvoke("photo-catalog:import", payload);
  },
  cancelOpenPhotoCatalog: () => safeInvoke("photo-catalog:cancel"),
  getDamCatalogStatus: (provider) => safeInvoke("photo-dam:status", { provider: String(provider || "") }),
  listDamCatalogs: (provider) => safeInvoke("photo-dam:list", { provider: String(provider || "") }),
  previewDamCatalog: (payload) => {
    assertPlainObject(payload, "DAM catalog preview payload");
    return safeInvoke("photo-dam:preview", payload);
  },
  importDamCatalog: (payload) => {
    assertPlainObject(payload, "DAM catalog import payload");
    return safeInvoke("photo-dam:import", payload);
  },
  syncDamCatalog: (payload) => {
    assertPlainObject(payload, "DAM catalog sync payload");
    return safeInvoke("photo-dam:sync", payload);
  },
  listInboundConnectors: () => safeInvoke("connectors:list"),
  saveInboundConnector: (payload) => safeInvoke("connectors:save", payload && typeof payload === "object" ? payload : {}),
  removeInboundConnector: (provider, connectionId) => safeInvoke("connectors:remove", { provider, connectionId }),
  invokeInboundConnector: (provider, connectionId, action, params = {}) => safeInvoke("connectors:invoke", { provider, connectionId, action, params }),
  getPhotosSensitiveAuthStatus: () => safeInvoke("photos:sensitive-auth-status"),
  authenticatePhotosSensitiveAccess: (reason = "") => safeInvoke("photos:authenticate-sensitive", { reason: String(reason || "").slice(0, 180) }),
  getWorkspaceLockStatus: () => safeInvoke("workspace-lock:get-status"),
  enableWorkspaceLock: () => safeInvoke("workspace-lock:enable"),
  lockWorkspace: () => safeInvoke("workspace-lock:lock"),
  unlockWorkspace: () => safeInvoke("workspace-lock:unlock"),
  disableWorkspaceLock: () => safeInvoke("workspace-lock:disable"),
  getWorkspaceEncryptionStatus: () => safeInvoke("workspace-encryption:get-status"),
  createWorkspaceRecoveryCode: () => safeInvoke("workspace-encryption:create-recovery-code"),
  rotateWorkspaceEncryptionKey: () => safeInvoke("workspace-encryption:rotate-key"),
  revealPath: (targetPath) => safeInvoke("shell:reveal-path", { path: targetPath }),
  openPath: (targetPath) => safeInvoke("shell:open-path", { path: targetPath }),
  openPhotoPrivacySettings: () => safeInvoke("shell:open-photo-privacy-settings"),
  openPathWith: (targetPath, editorPath = "") => safeInvoke("shell:open-path-with", { path: targetPath, editorPath }),
  listExternalEditors: () => safeInvoke("shell:list-external-editors"),
  forgetExternalEditor: (editorPath) => safeInvoke("shell:forget-external-editor", { editorPath }),
  sharePaths: (targetPaths) => safeInvoke("shell:share-paths", { paths: Array.isArray(targetPaths) ? targetPaths : [targetPaths] }),
  printPath: (targetPath) => safeInvoke("shell:print-path", { path: targetPath }),
  writeClipboardText: (text) => safeInvoke("clipboard:write-text", { text }),
  writeClipboardImagePath: (targetPath) => safeInvoke("clipboard:write-image-path", { path: targetPath }),
  startFileDrag: (targetPath) => safeInvoke("shell:start-drag-file", { path: targetPath }),
  getInitialState: () => safeInvoke("backend:initial-state"),
  rendererReady: () => safeInvoke("app:renderer-ready"),
  setAppLanguage: (language) => safeInvoke("app:set-language", { language }),
  getMcpConnectionInfo: () => safeInvoke("mcp:connection-info"),
  addMcpToCodex: () => safeInvoke("mcp:add-to-codex"),
  revealMcpConfigs: () => safeInvoke("mcp:reveal-configs"),
  revealOrBuildMcpBundle: () => safeInvoke("mcp:reveal-or-build-bundle"),
  startMcpHttpServer: () => safeInvoke("mcp:http-start"),
  stopMcpHttpServer: () => safeInvoke("mcp:http-stop"),
  getMcpHttpStatus: () => safeInvoke("mcp:http-status"),
  onMcpHttpStatus: (callback) => subscribe("mcp:http-status", callback),
  getMobileCompanionStatus: () => safeInvoke("mobile-companion:status"),
  configureMobileCompanion: (publicUrl) => safeInvoke("mobile-companion:configure", { publicUrl: String(publicUrl || "") }),
  createMobileCompanion: (options = {}) => safeInvoke("mobile-companion:create", options),
  revokeMobileCompanion: (accountId) => safeInvoke("mobile-companion:revoke", { accountId: String(accountId || "") }),
  onAppCommand: (callback) => subscribe("app:command", callback),
  onExternalOpen: (callback) => subscribe("app:external-open", callback),
  onScanProgress: (callback) => subscribe("backend:progress", callback),
  onBackendStartup: (callback) => subscribe("backend:startup", callback),
  onFolderWatch: (callback) => subscribe("folder-watch:event", callback),
  onPhotoTether: (callback) => subscribe("photo-tether:event", callback),
  onBackendError: (callback) => subscribe("backend:error", callback),
  onUpdateStatus: (callback) => subscribe("updater:event", callback),
  onDiagnosticsEvent: (callback) => subscribe("diagnostics:event", callback),
  platform: safePlatform,
  rendererGpuMode: safeEnv.CROSSAGE_RENDERER_GPU_MODE === "software" ? "software" : "hardware",
  testCamera: safeEnv.CROSSAGE_TEST_CAMERA === "1",
  testCameraError: safeEnv.CROSSAGE_TEST_CAMERA_ERROR === "1",
  testFileDropPathFallback: safeEnv.CROSSAGE_E2E_FILE_DROP_PATH_FALLBACK === "1"
}));
